#!/bin/sh
kill $(pgrep aesdsocket)
sudo ./aesdchar_unload
make clean
make
echo > /dev/null | sudo tee /var/log/syslog
echo > /dev/null | sudo tee /var/log/kern.log
sudo ./aesdchar_load
#../assignment-autotest/test/assignment8/drivertest.sh
